# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QIcon
from pytube import YouTube
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QGraphicsDropShadowEffect
from PyQt5.QtGui import QColor

video_previousprogress = 0
muzik_previousprogress = 0


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 594)

        ##---------
        ## Title bar kaldırıp arka planı yok etme
        MainWindow.setWindowFlag(Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        ##-------


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(10, 10, 10, 10)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.281716 rgba(85, 25, 170, 249), stop:0.645522 rgba(101, 24, 160, 245));\n"
"border-radius: 10px;\n"
"")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color: None;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(15, 8, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(184, 185, 255);")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setGeometry(QtCore.QRect(10, 10, 16, 16))
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_maximize.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setCheckable(False)
        self.btn_maximize.setChecked(False)
        self.btn_maximize.setAutoDefault(False)
        self.btn_maximize.setObjectName("btn_maximize")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setGeometry(QtCore.QRect(40, 10, 16, 16))
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setGeometry(QtCore.QRect(70, 10, 16, 16))
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("border-radius: 0px;\n"
"background-color: none;")
        self.content_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_bar)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_menu = QtWidgets.QFrame(self.content_bar)
        self.frame_menu.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.menu_frame_left = QtWidgets.QFrame(self.frame_menu)
        self.menu_frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame_left.setObjectName("menu_frame_left")
        self.horizontalLayout_7.addWidget(self.menu_frame_left)
        self.menu_frame_center = QtWidgets.QFrame(self.frame_menu)
        self.menu_frame_center.setMinimumSize(QtCore.QSize(500, 0))
        self.menu_frame_center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame_center.setObjectName("menu_frame_center")
        self.pushButton_5 = QtWidgets.QPushButton(self.menu_frame_center)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background-color: rgb(184, 185, 241);\n"
"    border-color: none;\n"
"    border-left-radius: 5px;\n"
"    padding-top: 6px;\n"
"    padding-bottom: 2px;\n"
"    color: rgb(10, 32, 172);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(184, 185, 241, 150);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.menu_frame_center)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background-color: rgb(184, 185, 241);\n"
"    border-color: none;\n"
"    border-right-radius: 5px;\n"
"    padding-top: 6px;\n"
"    padding-bottom: 2px;\n"
"    color: rgb(10, 32, 172);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(184, 185, 241, 150);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.menu_frame_center)
        self.menu_frame_right = QtWidgets.QFrame(self.frame_menu)
        self.menu_frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame_right.setObjectName("menu_frame_right")
        self.horizontalLayout_7.addWidget(self.menu_frame_right)
        self.verticalLayout_4.addWidget(self.frame_menu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_bar)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.video_page = QtWidgets.QWidget()
        self.video_page.setObjectName("video_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.video_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_content_video = QtWidgets.QFrame(self.video_page)
        self.frame_content_video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_video.setObjectName("frame_content_video")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_content_video)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_video = QtWidgets.QFrame(self.frame_content_video)
        self.frame_video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video.setObjectName("frame_video")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_video)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_video_left = QtWidgets.QFrame(self.frame_video)
        self.frame_video_left.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_video_left.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_video_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_left.setObjectName("frame_video_left")
        self.horizontalLayout_4.addWidget(self.frame_video_left)
        self.frame_video_mid = QtWidgets.QFrame(self.frame_video)
        self.frame_video_mid.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_video_mid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_mid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_mid.setObjectName("frame_video_mid")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_video_mid)
        self.lineEdit.setGeometry(QtCore.QRect(10, 120, 481, 31))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(184, 185, 241);\n"
"    color: rgb(10, 32, 172);\n"
"    border-color: none;\n"
"    border-radius: 8px;\n"
"    padding-left: 10px;\n"
"    padding-top: 2px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_video_mid)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 170, 431, 31))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(184, 185, 241);\n"
"    color: rgb(10, 32, 172);\n"
"    border-color: none;\n"
"    border-radius: 8px;\n"
"    padding-left: 10px;\n"
"    padding-top: 2px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.progressBar = QtWidgets.QProgressBar(self.frame_video_mid)
        self.progressBar.setGeometry(QtCore.QRect(10, 240, 481, 31))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(184, 185, 241);\n"
"    color: rgb(10, 32, 172);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.477, x2:1, y2:0.483, stop:0 rgba(247, 133, 255, 255), stop:1 rgba(148, 25, 255, 255));\n"
"    border-radius: 10px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(self.frame_video_mid)
        self.pushButton.setGeometry(QtCore.QRect(200, 310, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(184, 185, 241);\n"
"    border-color: none;\n"
"    border-radius: 5px;\n"
"    padding-top: 6px;\n"
"    padding-bottom: 2px;\n"
"    color: rgb(10, 32, 172);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(184, 185, 241, 150);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_video_mid)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 170, 41, 31))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(184, 185, 241);\n"
"    border-style: none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(184, 185, 241, 150);\n"
"}\n"
"")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(35, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.frame_video_mid)
        self.label.setGeometry(QtCore.QRect(10, 40, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(184, 185, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.frame_video_mid)
        self.frame_video_right = QtWidgets.QFrame(self.frame_video)
        self.frame_video_right.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_video_right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_video_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_right.setObjectName("frame_video_right")
        self.horizontalLayout_4.addWidget(self.frame_video_right)
        self.frame_video_right.raise_()
        self.frame_video_left.raise_()
        self.frame_video_mid.raise_()
        self.horizontalLayout_3.addWidget(self.frame_video)
        self.verticalLayout_5.addWidget(self.frame_content_video)
        self.stackedWidget.addWidget(self.video_page)
        self.music_page = QtWidgets.QWidget()
        self.music_page.setObjectName("music_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.music_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_content_music = QtWidgets.QFrame(self.music_page)
        self.frame_content_music.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_music.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_music.setObjectName("frame_content_music")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_content_music)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_music = QtWidgets.QFrame(self.frame_content_music)
        self.frame_music.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_music.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_music.setObjectName("frame_music")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_music)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_video_left_2 = QtWidgets.QFrame(self.frame_music)
        self.frame_video_left_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_video_left_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_video_left_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_left_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_left_2.setObjectName("frame_video_left_2")
        self.horizontalLayout_5.addWidget(self.frame_video_left_2)
        self.frame_video_mid_2 = QtWidgets.QFrame(self.frame_music)
        self.frame_video_mid_2.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_video_mid_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_mid_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_mid_2.setObjectName("frame_video_mid_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_video_mid_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 120, 481, 31))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(184, 185, 241);\n"
"    color: rgb(10, 32, 172);\n"
"    border-color: none;\n"
"    border-radius: 8px;\n"
"    padding-left: 10px;\n"
"    padding-top: 2px;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_video_mid_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 170, 431, 31))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(184, 185, 241);\n"
"    color: rgb(10, 32, 172);\n"
"    border-color: none;\n"
"    border-radius: 8px;\n"
"    padding-left: 10px;\n"
"    padding-top: 2px;\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.progressBar_2 = QtWidgets.QProgressBar(self.frame_video_mid_2)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 240, 481, 31))
        self.progressBar_2.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(184, 185, 241);\n"
"    color: rgb(10, 32, 172);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.477, x2:1, y2:0.483, stop:0 rgba(247, 133, 255, 255), stop:1 rgba(148, 25, 255, 255));\n"
"    border-radius: 10px;\n"
"}")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_video_mid_2)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 310, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(184, 185, 241);\n"
"    border-color: none;\n"
"    border-radius: 5px;\n"
"    padding-top: 6px;\n"
"    padding-bottom: 2px;\n"
"    color: rgb(10, 32, 172);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(184, 185, 241, 150);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_video_mid_2)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 170, 41, 31))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(184, 185, 241);\n"
"    border-style: none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(184, 185, 241, 150);\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(35, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.frame_video_mid_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(184, 185, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.frame_video_mid_2)
        self.frame_video_right_2 = QtWidgets.QFrame(self.frame_music)
        self.frame_video_right_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_video_right_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_video_right_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_right_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_right_2.setObjectName("frame_video_right_2")
        self.horizontalLayout_5.addWidget(self.frame_video_right_2)
        self.horizontalLayout_6.addWidget(self.frame_music)
        self.verticalLayout_6.addWidget(self.frame_content_music)
        self.stackedWidget.addWidget(self.music_page)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.content_bar)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.credits_bar.setFont(font)
        self.credits_bar.setStyleSheet("background-color: None;")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label_credits = QtWidgets.QFrame(self.credits_bar)
        self.frame_label_credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credits.setObjectName("frame_label_credits")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_label_credits)
        self.verticalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_credits = QtWidgets.QLabel(self.frame_label_credits)
        self.label_credits.setMinimumSize(QtCore.QSize(0, 0))
        self.label_credits.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(184, 185, 255);\n"
"")
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout_3.addWidget(self.label_credits)
        self.horizontalLayout_2.addWidget(self.frame_label_credits)
        self.frame_grip = QtWidgets.QFrame(self.credits_bar)
        self.frame_grip.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 28))
        self.frame_grip.setStyleSheet("padding: 5px;")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_2.addWidget(self.frame_grip)
        self.verticalLayout.addWidget(self.credits_bar)
        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Youtube Video | Müzik İndirme Programı"))
        self.pushButton_5.setText(_translate("MainWindow", "Video İndir"))
        self.pushButton_6.setText(_translate("MainWindow", "Müzik İndir"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Youtube linkini giriniz"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Kaydetmek istediğiniz yeri seçiniz"))
        self.pushButton.setText(_translate("MainWindow", "İndir"))
        self.label.setText(_translate("MainWindow", "YOUTUBE VİDEO İNDİR"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Youtube linkini giriniz"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Kaydetmek istediğiniz yeri seçiniz"))
        self.pushButton_2.setText(_translate("MainWindow", "İndir"))
        self.label_2.setText(_translate("MainWindow", "YOUTUBE MÜZİK İNDİR"))
        self.label_credits.setText(_translate("MainWindow", "Designer By: Cengizhan Erturan"))

        self.pushButton_6.clicked.connect(self.muzik_gec)
        self.pushButton_5.clicked.connect(self.video_gec)

        self.pushButton.clicked.connect(self.video_indir_btn)
        self.pushButton_2.clicked.connect(self.muzik_indir_btn)
        self.pushButton_3.clicked.connect(self.video_browse)
        self.pushButton_4.clicked.connect(self.muzik_browse)

        self.btn_minimize.clicked.connect(self.minimize)
        self.btn_close.clicked.connect(self.close)

        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(184, 185, 241, 150);\n"
                                        "    border-color: none;\n"
                                        "    border-left-radius: 5px;\n"
                                        "    padding-top: 6px;\n"
                                        "    padding-bottom: 2px;\n"
                                        "    color: rgb(10, 32, 172);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(184, 185, 241, 150);\n"
                                        "}")

    def muzik_gec(self):
            self.stackedWidget.setCurrentIndex(1)
            self.pushButton_6.setStyleSheet("QPushButton{\n"
                                            "    background-color: rgb(184, 185, 241, 150);\n"
                                            "    border-color: none;\n"
                                            "    border-left-radius: 5px;\n"
                                            "    padding-top: 6px;\n"
                                            "    padding-bottom: 2px;\n"
                                            "    color: rgb(10, 32, 172);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(184, 185, 241, 150);\n"
                                            "}")
            self.pushButton_5.setStyleSheet("QPushButton{\n"
                                            "    background-color: rgb(184, 185, 241);\n"
                                            "    border-color: none;\n"
                                            "    border-left-radius: 5px;\n"
                                            "    padding-top: 6px;\n"
                                            "    padding-bottom: 2px;\n"
                                            "    color: rgb(10, 32, 172);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(184, 185, 241, 150);\n"
                                            "}")

    def video_gec(self):
            self.stackedWidget.setCurrentIndex(0)
            self.pushButton_5.setStyleSheet("QPushButton{\n"
                                            "    background-color: rgb(184, 185, 241, 150);\n"
                                            "    border-color: none;\n"
                                            "    border-left-radius: 5px;\n"
                                            "    padding-top: 6px;\n"
                                            "    padding-bottom: 2px;\n"
                                            "    color: rgb(10, 32, 172);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(184, 185, 241, 150);\n"
                                            "}")
            self.pushButton_6.setStyleSheet("QPushButton{\n"
                                            "    background-color: rgb(184, 185, 241);\n"
                                            "    border-color: none;\n"
                                            "    border-left-radius: 5px;\n"
                                            "    padding-top: 6px;\n"
                                            "    padding-bottom: 2px;\n"
                                            "    color: rgb(10, 32, 172);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(184, 185, 241, 150);\n"
                                            "}")

    def video_progress(self, stream, chunk, bytes_remaining):
            global video_previousprogress
            total_size = stream.filesize
            bytes_downloaded = total_size - bytes_remaining

            liveprogress = (int)(bytes_downloaded / total_size * 100)
            if liveprogress > video_previousprogress:
                    video_previousprogress = liveprogress
                    self.progressBar.setValue(liveprogress)
                    QApplication.processEvents()

    def muzik_progress(self, stream, chunk, bytes_remaining):
            global muzik_previousprogress
            total_size = stream.filesize
            bytes_downloaded = total_size - bytes_remaining

            liveprogress = (int)(bytes_downloaded / total_size * 100)
            if liveprogress > muzik_previousprogress:
                    muzik_previousprogress = liveprogress
                    self.progressBar_2.setValue(liveprogress)
                    QApplication.processEvents()

    def video_indir_btn(self):
            download_url = self.lineEdit.text()
            list = self.lineEdit_2.text().split("/")
            dosya_ismi = list.pop()
            dosya_yolu = ""
            for i in list:
                    dosya_yolu += i + "/"
            yt = YouTube(download_url)
            yt.register_on_progress_callback(self.video_progress)
            yt.streams.filter(only_audio=False).first().download(dosya_yolu, dosya_ismi)
            global video_previousprogress
            video_previousprogress = 0
            self.progressBar.setValue(0)
            self.lineEdit_2.setText("")
            self.lineEdit.setText("")
            self.msgbox = QtWidgets.QMessageBox()
            self.msgbox.setWindowIcon(QIcon("icons/icon.ico"))
            self.msgbox.addButton(QtWidgets.QPushButton('Tamam'), QtWidgets.QMessageBox.YesRole)
            self.msgbox.setIcon(QtWidgets.QMessageBox.Information)
            self.msgbox.setWindowTitle("Bilgilendirme")
            self.msgbox.setText(
                    "İndirme işlemi başarılı bir şekilde gerçekleştirilmiştir.")
            self.msgbox.show()

    def muzik_indir_btn(self):
            download_url = self.lineEdit_3.text()
            list = self.lineEdit_4.text().split("/")
            dosya_ismi = list.pop()
            dosya_yolu = ""
            for i in list:
                    dosya_yolu += i + "/"
            yt = YouTube(download_url)
            yt.register_on_progress_callback(self.muzik_progress)
            yt.streams.filter(only_audio=True).first().download(dosya_yolu, dosya_ismi)
            global muzik_previousprogress
            muzik_previousprogress = 0
            self.progressBar_2.setValue(0)
            self.lineEdit_4.setText("")
            self.lineEdit_3.setText("")
            self.msgbox = QtWidgets.QMessageBox()
            self.msgbox.setWindowIcon(QIcon("icons/icon.ico"))
            self.msgbox.addButton(QtWidgets.QPushButton('Tamam'), QtWidgets.QMessageBox.YesRole)
            self.msgbox.setIcon(QtWidgets.QMessageBox.Information)
            self.msgbox.setWindowTitle("Bilgilendirme")
            self.msgbox.setText(
                    "İndirme işlemi başarılı bir şekilde gerçekleştirilmiştir.")
            self.msgbox.show()

    def video_browse(self):
            save_location = QFileDialog.getSaveFileName(caption="Save As", directory=".", filter=".mp4")
            self.lineEdit_2.setText(str(save_location[0]))

    def muzik_browse(self):
            save_location = QFileDialog.getSaveFileName(caption="Save As", directory=".", filter=".mp4")
            self.lineEdit_4.setText(str(save_location[0]))

    def percent_video(self, tem_video, total_video):
            perc_video = (float(tem_video) / float(total_video)) * float(100)
            return perc_video

    def percent_muzik(self, tem_muzik, total_muzik):
            perc_muzik = (float(tem_muzik) / float(total_muzik)) * float(100)
            return perc_muzik

    def minimize(self):
            self.showMinimized()

    def close(self):
            self.close()

    def mousePressEvent(self, event):  # +
            self.dragPos = event.globalPos()

    def mouseMoveEvent(self, event):  # !!!
            if event.buttons() == QtCore.Qt.LeftButton:
                    self.move(self.pos() + event.globalPos() - self.dragPos)
                    self.dragPos = event.globalPos()
                    event.accept()

## Pyqt5 'in olusturdugu kodlara dokunmak yerıne baska bır class ac ve orada ıslem yap(Miras al)!!
class MyWin(QtWidgets.QMainWindow, Ui_MainWindow):
        def __init__(self):
                super().__init__()
                self.setupUi(self)
                self.dragPos = QtCore.QPoint()  ##Pencere hareket ettirmek icin
                self.shadow = QGraphicsDropShadowEffect(self)
                self.shadow.setBlurRadius(20)
                self.shadow.setXOffset(0)
                self.shadow.setYOffset(0)
                self.shadow.setColor(QColor(0, 0, 0, 60))
                self.drop_shadow_frame.setGraphicsEffect(self.shadow)

        def mousePressEvent(self, event):  ##Pencere hareket ettirmek icin
                self.dragPos = event.globalPos()

        def mouseMoveEvent(self, event):  ##Pencere hareket ettirmek icin
                if event.buttons() == QtCore.Qt.LeftButton:
                        self.move(self.pos() + event.globalPos() - self.dragPos)
                        self.dragPos = event.globalPos()
                        event.accept()



import photo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # MainWindow = QtWidgets.QMainWindow()
    # ui = Ui_MainWindow()
    # ui.setupUi(MainWindow)
    # MainWindow.show()
    w = MyWin()
    w.show()
    sys.exit(app.exec_())
